### ISSUE TITLE
Data doesn't refresh when selecting a new country on map

### ISSUE THREAD

**Issue by janus-rose** [digitalfreedom/website#2]
When clicking on countries on the map, the previously clicked country's data still appears in the pop-up after a second country is clicked. The correct data is displayed when user clicks a different tab and then back to the desired tab.

Tested in Chrome + Firefox

Expected behaviour: Clicking on a new country refreshes the pop-up to display the correct data

**Comment by botherder** [comment]
It is true, you need to switch tabs to refresh the data.
