### ISSUE TITLE
Create data package viewer

### ISSUE THREAD

**Issue by botherder** [digitalfreedom/website#6]
Would be useful to have a full data package viewer, similarly to what GitHub does. We could use https://www.datatables.net/ for that purpose.

**Comment by bnvk** [comment]
@botherder i've implemented basic support for viewing DataTables on the `/datasets/` page. Give it a look over- some of the packages force the width too large and looks kinda ugly, but overall it works!

To see this update, in addition to doing the Jekyll build stuff, you need to add the "data-toc" package to the allowed packages in ConjurorAPI config.json file though to make it work!
